# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none
stages:
- stage: QA
  displayName: 'Test Rest Webservices'
  jobs:
  - job: 'Test_Rest_Services'
    pool:
      vmImage: ubuntu-latest
    steps:  
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo Build is completed
          pwd
          mkdir data
          cd data
          pwd
          touch file345.txt
          ls -l
    - task: CopyFiles@2
      inputs:
        Contents: '/home/vsts/work/1/s/data/file345.txt'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo Copying is completed
          azcopy copy '$(Build.ArtifactStagingDirectory)' 'https://reportdump.blob.core.windows.net/images?sv=2020-02-10&ss=bfqt&srt=sco&sp=rwdlacuptfx&se=2021-06-15T13:05:47Z&st=2021-06-15T05:05:47Z&spr=https&sig=PK8njPmgGs0fAT6SGdBbVyKwF%2Bk%2FhMEP%2FxHa6t3vbxk%3D' --recursive
         


