# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none
stages:
- stage: Dev
  displayName: 'Build_Rest_Services'
  jobs:
  - job: 'Generate_War'
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          pwd
          mkdir pipeline-backend-main
          cd pipeline-backend-main
          mkdir target
          cd target
          touch dep.war
          pwd
          ls
    - task: CopyFiles@2
      inputs:
        Contents: '**/pipeline-backend-main/target/*.war'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/pipeline-backend-main/target'
        ArtifactName: 'RestBuild'
        publishLocation: 'Container'
- stage: Deploy
  displayName: "Deploy in Tomcat"
  jobs:
  - job: 'Deploy'
    timeoutInMinutes: 10
    pool: ecom-pool
    steps:
    - checkout: none 
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'RestBuild'
        itemPattern: '**/*.war'
        downloadPath: '$(Build.ArtifactStagingDirectory)/test'
    - script: pwd
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          which java
          pwd
          sudo cp $(Build.ArtifactStagingDirectory)/test/dep.war /opt/tomcat/webapps
         
 








