# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none
stages:
- stage: QA
  displayName: 'Test Rest Webservices'
  jobs:
  - job: 'Test_Rest_Services'
    pool:
      vmImage: ubuntu-latest
    steps:  
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo Build is completed
          pwd
          mkdir data
          cd data
          touch file345.txt
    - task: CopyFiles@2
      inputs:
        Contents: '/home/vsts/work/1/s/data'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo Copying is completed
          azcopy cp '$(Build.ArtifactStagingDirectory)' 'https://reportdump.blob.core.windows.net/images?sp=r&st=2021-06-15T04:52:41Z&se=2021-06-15T12:52:41Z&spr=https&sv=2020-02-10&sr=c&sig=KdLMoVEZFvYo7nah7wgSZMPsFiGTQBCp08K3Fp57j8Q%3D' --recursive
         
         


